// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDslV6X-VF9e1IfWtekfRQde8d_Pl89EoE',
    appId: '1:92678655550:web:1b04439ed2316b4e534b6f',
    messagingSenderId: '92678655550',
    projectId: 'chat-app-21982',
    authDomain: 'chat-app-21982.firebaseapp.com',
    storageBucket: 'chat-app-21982.appspot.com',
    measurementId: 'G-0Z74TCFZGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3-Bb9ZxhD3ZA1DOfr5aKdUu_KGLdANr4',
    appId: '1:92678655550:android:7ea62c5d965228dc534b6f',
    messagingSenderId: '92678655550',
    projectId: 'chat-app-21982',
    storageBucket: 'chat-app-21982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzp_UoJwBqh5z68ORRYRUZ-4WKLKReNQY',
    appId: '1:92678655550:ios:dc773941e234f860534b6f',
    messagingSenderId: '92678655550',
    projectId: 'chat-app-21982',
    storageBucket: 'chat-app-21982.appspot.com',
    androidClientId: '92678655550-ektdv1gkfh2kire2ehvevnlcab4emtn9.apps.googleusercontent.com',
    iosClientId: '92678655550-hi4o8lgacaglg09jbln07g5ugrd5s3gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzp_UoJwBqh5z68ORRYRUZ-4WKLKReNQY',
    appId: '1:92678655550:ios:dc773941e234f860534b6f',
    messagingSenderId: '92678655550',
    projectId: 'chat-app-21982',
    storageBucket: 'chat-app-21982.appspot.com',
    androidClientId: '92678655550-ektdv1gkfh2kire2ehvevnlcab4emtn9.apps.googleusercontent.com',
    iosClientId: '92678655550-hi4o8lgacaglg09jbln07g5ugrd5s3gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
